sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t eshuster/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true eshuster/docker-react npm run test
